#!/bin/bash
#
# Copyright (C) 2011 Eamon Millman
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#

if [ $# -gt 2 ]; then
	valgrind --tool=callgrind ./model/manet -u Cmdenv -c $1 -r $2 -n ./model/ned -l ./model/inet -l ./model/stars-opp ./model/$3
else
	exit 1
fi
