#!/bin/bash
#
# Copyright (C) 2011 Eamon Millman
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#

ECODE=1
if [ $# -gt 1 ]; then
	./model/manet -x $1 -n ./model/ned -l ./model/inet -l ./model/stars-opp ./model/$2
	ECODE=$?
else
	./model/manet -a -n ./model/ned -l ./model/inet -l ./model/stars-opp ./model/$1
	ECODE=$?
fi
exit $ECODE
