#!/bin/bash

source env.sh

if [ $RHOST ]; then
	LINE="ssh $RHOST 'cd $SPATH && git pull && git up && ./package && ./deploy $DPATH'"
else
	LINE="cd $SPATH && git pull && git up && ./package && ./deploy $DPATH"
fi
eval $LINE
