#!/bin/bash

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $RHOST ]; then
	LINE="ssh $RHOST 'cd $SPATH && git pull && git up && ./package && ./deploy $DPATH'"
else
	LINE="cd $SPATH && git pull && git up && ./package && ./deploy $DPATH"
fi
eval $LINE
