#!/bin/bash
#
# shows information about currently running processes

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $RHOST ]; then
	if [ $# -eq 0 ]; then
		ssh "$RHOST" "cat '$DPATH/log/info.log'"
	fi;
	if [ $# -eq 1 ]; then
		ssh "$RHOST" "cat '$DPATH/out-stars.log' | grep '$1'"
	fi;
else
	if [ $# -eq 0 ]; then
		cat "$DPATH/log/info.log"
	fi;
	if [ $# -eq 1 ]; then
		cat "$DPATH/out-stars.log" | grep "$1"
	fi;
fi;
