#!/bin/bash
#
# modify process priority value
# param 1: process id
# param 2: new priority, interger value, reletive to concurrent processes

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 2 ]; then
	echo setting process $1 to priority $2
	if [ $RHOST ]; then
		ssh "$RHOST" "touch '$DPATH/work/$1.$2.priority'"
	else
		touch "$DPATH/work/$1.$2.priority"
	fi
else
        echo "usage: ./priority <process id> <priority>"
        echo "to obtain the process id ./info"
fi;
