#!/bin/bash
# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

echo "registering user's public key with STARS"

scp $HOME/.ssh/id_rsa.pub $RHOST:~/temp.pk
ssh $RHOST 'cat temp.pk >> ~/.ssh/authorized_keys; rm temp.pk'
echo "regisering clts's public key with user"
scp $RHOST:~/.ssh/id_rsa.pub $HOME/temp.pk
cat $HOME/temp.pk >> $HOME/.ssh/authorized_keys 
rm $HOME/temp.pk
