#!/bin/bash
#
# release worker by id
# param 1: worker id

if [ $# -eq 1 ]; then
	echo releasing worker $1
	if [ $RHOST ]; then
		
		LINE="ssh $RHOST 'touch $DPATH/work/$1.release'"
	else
		LINE="touch $DPATH/work/$1.release"
	fi;
	eval $LINE
else
        echo "usage: ./release <worker id>"
        echo "to obtain the worker id ./info"
fi;
