#!/bin/bash
#
# release worker by id
# param 1: worker id

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 1 ]; then
	echo releasing worker $1
	if [ $RHOST ]; then
		
		LINE="ssh $RHOST 'touch $DPATH/work/$1.release'"
	else
		LINE="touch $DPATH/work/$1.release"
	fi;
	eval $LINE
else
        echo "usage: ./release <worker id>"
        echo "to obtain the worker id ./info"
fi;
