#!/bin/bash
#
# terminate the system!
# shuts down all running processes gracefully
# kills all running process tasks.
#

########################################
# Config, etc
########################################

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

function print_usage () {
	SCRIPT_NAME="$( basename "${BASH_SOURCE[0]}" )"
        echo "
Usage:
	$SCRIPT_NAME confirm

	Forcefully shuts down the STARS cluster.
"
	exit ${1:-0}
}

########################################
# Script
########################################
[[ $# -ne 1 ]] && print_usage 1
[[ $1 == "-h" || $1 == "--help" || $1 != 'confirm' ]] && print_usage

echo sending shutdown now request
if [ -n "$RHOST" ]; then
	ssh "$RHOST" "touch '$DPATH/work/shutdown.now'"
else
	touch "$DPATH/work/shutdown.now"
fi
