#!/bin/bash
#
# terminate the system!
# shuts down all running processes gracefully
# kills all running process tasks.
#

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [[ $# -eq 1 &&  $1 == 'confirm' ]]; then
	echo sending shutdown now request
	if [ $RHOST ]; then
		ssh "$RHOST" "touch '$DPATH/work/shutdown.now'"
	else
		touch "$DPATH/work/shutdown.now"
	fi
else
	echo "missing argument, type: ./shutdown confirm"
	echo "to perform the shutdown"
fi;
