#!/bin/bash

########################################
# Config, etc
########################################

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

function print_usage () {
	SCRIPT_NAME="$( basename "${BASH_SOURCE[0]}" )"
        echo "
Usage:
	$SCRIPT_NAME <NUMBER_OF_NODES>

	Start up the STARS cluster with specified number of processing nodes available.

	NUMBER_OF_NODES - Number of processing nodes PLUS 1 (for the management node)
"
	exit ${1:-0}
}

########################################
# Script
########################################
[[ $# -ne 1 ]] && print_usage 1
[[ $1 == "-h" || $1 == "--help" ]] && print_usage

echo "stars start request sent for $1 processes"
if [ -n "$RHOST" ]; then
	ssh "$RHOST" "cd '$DPATH' && ./starsbg '$1'"
else
	cd "$DPATH" && ./starsbg "$1"
fi
