#!/bin/bash

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 1 ]; then
	echo stars start request sent for $1 processes
	if [ $RHOST ]; then
		LINE="ssh $RHOST 'cd $DPATH && ./starsbg $1'"
	else
		LINE="cd $DPATH && ./starsbg $1"
	fi
	eval $LINE
fi;
