#!/bin/bash
#
# Start the specified workfiles

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

function die () {
	[ -n "$1" ] && echo "$1" >&2
	exit 1
}

while [ "$#" -ne 0 ]; do
	echo "Processing workfile: $1"
	WORKFILE="$( basename "$1" )"

	if [ $RHOST ]; then
		scp "$1" "$RHOST:$DPATH/work/$WORKFILE.tmp" || die "Unable to send workfile to managment node"
		ssh "$RHOST" "mv '$DPATH/work/$WORKFILE.tmp $DPATH/work/$WORKFILE'" || die "Failed to submit workfile"
	else
		stat "$1" || die "Unable to send workfile to managment node"
		cp "$1" "$DPATH/work/" || die "Failed to submit workfile"
	fi

	shift
done

