#!/bin/bash
#
# immediately stop the process 
# param 1: process id

SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 1 ]; then
	echo requesting to stop process $1 now
	if [ $RHOST ]; then
		
		LINE="ssh $RHOST 'touch $DPATH/work/$1.kill'"
	else
		LINE="touch $DPATH/work/$1.kill"
	fi;
	eval $LINE
else
        echo "usage: ./stopnow <process id>"
	echo "to obtain the process id run ./info"
fi;
