#!/bin/bash
#
# gracefully stop the process
# param 1: process id

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -gt 0 ]; then
	for process in "$@"; do
		echo requesting to stop process "$process"
		if [ -n $RHOST ]; then
			ssh "$RHOST" "touch '$DPATH/work/${process}.stop'"
		else
			touch "$DPATH/work/${process}.stop"
		fi;
	done
else
        echo "usage: ./stop <process id>"
	echo "to obtain the process id run ./info"
fi;
