#!/bin/bash
#
# gracefully stop the process 
# param 1: process id

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 1 ]; then
	echo requesting to stop process $1
	if [ $RHOST ]; then
		ssh "$RHOST" "touch '$DPATH/work/$1.stop'"
	else
		touch "$DPATH/work/$1.stop"
	fi;
else
        echo "usage: ./stop <process id>"
	echo "to obtain the process id run ./info"
fi;
