#!/bin/bash
#
# gracefully stop the process
# param 1: process id

########################################
# Config, etc
########################################

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

function print_usage () {
	SCRIPT_NAME="$( basename "${BASH_SOURCE[0]}" )"
        echo "
Usage:
	$SCRIPT_NAME <PROCESS_ID1> [PROCESS_ID2 [...]]

	Gracefully stop the specified processes.
	To obtain a list of process IDs, run the 'info' command.

	PROCESS_ID# - ID of the specified process.
"
	exit ${1:-0}
}

########################################
# Script
########################################
[[ $# -eq 0 ]] && print_usage 1
[[ $1 == "-h" || $1 == "--help" ]] && print_usage

for process in "$@"; do
	echo requesting to stop process "$process"
	if [ -n "$RHOST" ]; then
		ssh "$RHOST" "touch '$DPATH/work/${process}.stop'"
	else
		touch "$DPATH/work/${process}.stop"
	fi;
done
