#!/bin/bash
#
# modify process workers value
# param 1: process id
# param 2: new workers, interger value greater than zero.
#		how many nodes to allocate

# Quit if any command fails or if a variable is unbound
set -e -o nounset

# If launched through a symlink, check for an env.sh file in that directory.
# If that does not exist, use the one in the script's actual location.
SCRIPT_DIR="$( dirname "${BASH_SOURCE[0]}" )"
[ -r "${SCRIPT_DIR}/env.sh" ] || SCRIPT_DIR="$( dirname "$(readlink -e "${BASH_SOURCE[0]}")" )"
source "${SCRIPT_DIR}/env.sh"

if [ $# -eq 2 ]; then
	echo setting process $1 to use $2 nodes
	if [ $RHOST ]; then

		ssh "$RHOST" "touch '$DPATH/work/$1.$2.workers'"
	else
		touch "$DPATH/work/$1.$2.workers"
	fi;
else
        echo "usage: ./workers <process id> <min workers>"
        echo "to obtain the process id run ./info"
fi;
