% this file defines the random features used to test the analysis engine
% implementation

% import the constants which define different statisticals available
statenv;

% declare which statistics to calculate vs time for a feature. The variable
% is a cell array of tuples defining the statistic used when sampling and
% then estimating the feature. each element in the cell array produces its
% own result.
stats = { ...
    [STAT_COUNT STAT_MIN], ... % [ sample estimate ]
    [STAT_COUNT STAT_MAX], ...
    [STAT_COUNT STAT_MEAN], ...
    [STAT_COUNT STAT_MEDIAN], ...
    [STAT_MIN, STAT_MIN], ...
    [STAT_MAX, STAT_MAX], ...
    [STAT_MEAN, STAT_MEAN] ...
    };

% features = {} should already be defined and may already contain existing
% entries. therefore, always append new features to the end of the cell
% array.

%%{
% new features should be created with a call to featureNew
features{end+1} = featureNew('test_2modes', ... % this is a unique name for the feature
    'ts2Mode',{}, ... % this is the function name to load the feature data from, and the cell array of function parameters
    stats, ... % these are the time-series averages to produce for feature data
    'uniform and exponential modes', 'value' ); % this is the feature title, and units used for reporting and plotting.
%}
%%{
features{end+1} = featureNew('test_Nmodes', ...
    'tsNMode',{}, ...
    stats, ...
    'N modes', 'value' );
%}
%%{
features{end+1} = featureNew('test_mode_uni', ...
    'tsMode',{}, ...
    stats, ...
    'uniform mode', 'value' );
%}
%%{
features{end+1} = featureNew('test_mode_uni_discrete', ...
    'tsModeDiscrete',{}, ...
    stats, ...
    'uniform mode', 'discrete value' );
%}
