#!/bin/bash
#
# Copyright (C) 2011 Eamon Millman
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#

if [ $# -eq 4 ]; then
	cd $1
	tar zcf $2_$3_r$4.tar.gz $2*-$3-$4.log && rm -f $2*-$3-$4.log
	if [ $? -ne 0 ]; then
		exit 1
	else
		exit 0
	fi
else
	echo "usage: ./compress path prefix config run"
	exit 1
fi
