#!/bin/bash
#
# Copyright (C) 2011 Eamon Millman
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#

#source env.sh

if [ $# -eq 2 ]; then
	
	matlab -nodisplay -nosplash -r "rcode = 1; try; addpath(genpath('matlab'),0); rcode = $1( '$2' ); catch me; display( me.identifier ); display( me.message ); for i = 1:length( me.stack ); display( me.stack(i) ); end; end; exit( rcode );"
	if [ $? -ne 0 ]; then
		exit 1
	else
		exit 0
	fi
else
	exit 1
fi
